services:
  db:
    image: postgres:16
    container_name: plathanus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plathanus_real_estate_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - plathanus-network

  minio:
    image: minio/minio:latest
    container_name: plathanus-minio
    ports:
      - "9000:9000"      # API
      - "9001:9001"      # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - plathanus-network

  # ServiÃ§o auxiliar para criar o bucket automaticamente
  createbuckets:
    image: minio/mc:latest
    container_name: plathanus-createbuckets
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do 
        echo 'Aguardando MinIO estar pronto...' && sleep 2; 
      done;
      /usr/bin/mc mb myminio/plathanus-real-estate-development --ignore-existing;
      echo 'Bucket criado com sucesso!';
      exit 0;
      "
    networks:
      - plathanus-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plathanus-web
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      PORT: 3001
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: plathanus_real_estate_development
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_ACCESS_KEY: minioadmin
      MINIO_REGION: us-east-1
      MINIO_BUCKET: plathanus-real-estate-development
      ACTIVE_STORAGE_SERVICE: minio
      RAILS_CORS_ORIGINS: http://0.0.0.0:3000,http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      createbuckets:
        condition: service_completed_successfully
    stdin_open: true
    tty: true
    networks:
      - plathanus-network

volumes:
  postgres_data:
  minio_data:
  bundle_cache:

networks:
  plathanus-network:
    name: plathanus-network
    driver: bridge

